version: '3'
services:
  nginx:
    build:
      context: '.'
    volumes:
      - '${APP_CODE_PATH_HOST}:${APP_CODE_PATH_NGINX}${APP_CODE_CONTAINER_FLAG}'
    ports:
      - '${NGINX_HOST_HTTP_PORT}:80'
volumes: {}
